version: '3.3'

services:
  neo4j:
    image: neo4j:5.8.0-community
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - mito-network

  graph-ms:
    build:
      context: .
      dockerfile: ci/Dockerfile
    container_name: graph-ms
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
    environment:
      - SPRING_NEO4J_URI=bolt://neo4j:7687
      - SPRING_NEO4J_AUTHENTICATION_USERNAME=neo4j
      - SPRING_NEO4J_AUTHENTICATION_PASSWORD=password
    networks:
      - mito-network

volumes:
  neo4j-data:
  neo4j-logs:

networks:
  mito-network:
    driver: bridge