spring:
  neo4j:
    uri: bolt://neo4j:7687
    authentication:
      username: neo4j
      password: password

# Configurazioni OpenAPI
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Configurazioni del server
server:
  port: 8080